pipeline {
    agent any
    
    stages {
        stage('Pull Image') {
            steps {
                sh 'docker pull deepakkumarkhatri/cat-dog-fast-api:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }   
}
